#!/usr/bin/env bash

sudo apt update
sudo apt install build-essential curl fd-find fzf git git-lfs nvim python3 python3-venv ripgrep stow tmux wget xsel zsh zsh-common zsh-doc

git lfs install

 git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
 ~/.tmux/plugins/tpm/scripts/install_plugins.sh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

stow -t ~ nvim
stow -t ~ oh-my-zsh
stow -t ~ tmux

