#!/usr/bin/env bash

sudo apt update
sudo apt install git git-lfs build-essential curl wget python3-venv python3-pynvim fd-find ripgrep tmux xsel

git lfs install

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/scripts/install_plugins.sh

